version: '3'
services:
  nodejs-server:
    build:
      context: ./
      dockerfile: Dockerfile-fake-backend
    ports:
      - "3000:3000"
    container_name: spoteezer-json-server
  angular-ui:
    build:
      context: ./
      dockerfile: Dockerfile-angular-ui
    ports:
      - "80:80"
    container_name: spoteezer-angular-ui